# Use of /** so that the configurations hold for controller
# managers regardless of their namespace. Usefull in multi-robot setups.
/**/controller_manager:
  ros__parameters:
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

/**/position_trajectory_controller:
  ros__parameters:
    joints:
      - lbr_right_A1
      - lbr_right_A2
      - lbr_right_A3
      - lbr_right_A4
      - lbr_right_A5
      - lbr_right_A6
      - lbr_right_A7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

/**/forward_position_controller:
  ros__parameters:
    joints:
      - lbr_right_A1
      - lbr_right_A2
      - lbr_right_A3
      - lbr_right_A4
      - lbr_right_A5
      - lbr_right_A6
      - lbr_right_A7
    interface_name: position
